### ISSUE TITLE
Change tracking issues through user events instead

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/helpful-tools#6]
Mục tiêu là phải lấy được toàn bộ những commits trên mọi public repo (cụ thể vào từng branch) của các user

https://docs.github.com/en/rest/activity/events#list-events-for-the-authenticated-user

**Comment by MasterPi-2124** [comment]
so right now how are we tracking? I can see that we start tracking from activeMembers -> activeRepo -> commits

**Comment by nghuyenthevinh2000** [comment]
> so right now how are we tracking? I can see that we start tracking from activeMembers -> activeRepo -> commits

![Screenshot from 2022-06-06 09-20-30](https://user-images.githubusercontent.com/23058164/172083947-8ae23a49-4f2c-4e95-b486-6c65c6e512fa.png)

**Comment by nghuyenthevinh2000** [comment]
proof that this is done?

**Comment by nghuyenthevinh2000** [comment]
@MasterPi-2124
