### ISSUE TITLE
Tool for auto - restake and auto - claim

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/helpful-tools#7]
plan:

1. Ricardo will authorize developer address for two actions: claim and stake. There will be a fast script for this.
2. Tool will automatically re - stake and claim everyday.
3. Tool will automatically write down profit to an excel file everyday on these four attributes:

- Stake Reward
- Val Commission
- Total Income
- Income (USD) (get token price from coingecko)

4. There will be an option to exclude re - stake for specific validators in case we need money.

document:

1. https://docs.cosmos.network/master/modules/authz/
2. https://github.com/cosmos/cosmos-sdk/blob/main/x/authz/client/cli/tx.go#L96
3. https://github.com/notional-labs/notional/issues/56

**Comment by hieuvubk** [comment]
@nghuyenthevinh2000 i need information about our validators like this format. Just care about chain name & validator address
![image](https://user-images.githubusercontent.com/72878483/167308979-c66a0cd0-7d06-425c-b63f-96f35da0f8cd.png)

**Comment by nghuyenthevinh2000** [comment]
@mgialong215 
ông ơi, cho Hiếu thông tin như trên

**Comment by hieuvubk** [comment]
The tool look like that but need someday to confirm it work stably
![Screenshot from 2022-05-10 01-28-21](https://user-images.githubusercontent.com/72878483/167474754-76a956c1-0c2c-4a25-896d-a383187a005d.png)
Code available at [restake-tool](https://github.com/notional-labs/restake-tools)
